### ISSUE TITLE
C 言語に由来する名前の名前空間について

### ISSUE THREAD

**Issue by kariya-mitsuru** [starpos/get-out-of-cpp-beginners#2]
規格上、C 言語に由来する関数や `typedef` は全て `std` 名前空間に存在するとされていて、グローバル名前空間にあるかどうかは未規定となっているため、`std` 名前空間から使用した方が良いのではないかと思います。
`puts` とか `printf` とか `size_t` とか…

cf. http://eel.is/c++draft/headers#4

**Comment by starpos** [comment]
コメントありがとうございます。
これは STL と C 言語でも使える関数を区別したい私のクセなのですが、実際に困る事態にならないと改善される見込みがないため、この本では注釈だけしておくことにします。

**Comment by starpos** [comment]
c05582c277fbc94fb5826801d45a1159e68cdfb6
こんな感じに書きました。
