### ISSUE TITLE
配置 new の呼び出し方について

### ISSUE THREAD

**Issue by kariya-mitsuru** [starpos/get-out-of-cpp-beginners#3]
[memory.md](https://github.com/starpos/get-out-of-cpp-beginners/blob/master/memory.md) の 284、301 行目ですが、配置 `new` は常に `::new(p)` とした方が良いと思います。
この例の場合だと、`::` が無いと万一 `A` に `operator new(std::size_t, void*)` が定義されているとそちらが呼ばれてしまいます。
（そんなもの定義するヤツは普通いませんが…）

また、紙面の制約があるので厳しいかもしれませんが、個人的には `A` に `operator new` と `operator delete` を定義する方法がより自然ではないかと思います。
（構築や破棄自体に小細工する必要が無いため）

cf. C++14 までの場合：https://wandbox.org/permlink/qvZ5jM5E0w8goFdR
cf. C++17 からの場合：https://wandbox.org/permlink/IlyaCdw5d6MiyxeU

**Comment by starpos** [comment]
`::new` と `new` の区別を本書の読者にさせるのは目的を逸脱していると考えます。
また、私は、どちらかだけを書くべきかと問われれば `new` の方です。。operator new をわざわざ定義する人がいれば、それを使ってもらうべくしてそうしていると思いますので。

ご提示の方法はよりスマートだと思います。ただ、C++11 から C++17 にかけて劇的に変化しているインターフェースなので、C++17 以降が当たり前になった暁にはそれを採用したいなと思います。また、今回のご指摘を受けてちょっと調べてみて operator new および delete には罠がいっぱいありそうだと感じたので、出来れば触れたくないです。。(主にオーバーロード回り)

本書では、現時点では operator new および delete を使う方法がある(しかしインターフェースがどんどん変わっているので注意)と書いて C++17 の例だけ示しておこうと思います。

**Comment by starpos** [comment]
2644343fdf8928b62873ed54714eedd8a4f84d7c
こんな感じにしました。

**Comment by kariya-mitsuru** [comment]
すみません、私の元のコメントが完全に意味不明でした…
私も `::new` と `new` の区別をさせるべきであると考えているわけではありません。

私の意見としては、new の 284、301 行目の使い方、つまり「指定されたアドレスにオブジェクトを構築する方法」としてはなんぴとたりともこの書き方をすべきではなく必ず `::new A(p)` と記載すべきであり、たとえ初心者に対しても（むしろ初心者に対してこそ）この方法を教える時には初めから `::new A(p)` と書くんだと教えるべきである（たとえおまじないだと言ったとしても）、と言うものです。

その理由としては、元のコメントに書いたことも発生し得ますが（多分発生しない）、むしろ初心者がこの記法（`new A(p)`）を「指定されたアドレスにオブジェクトを構築する方法」として学習した後、何らかのライブラリで提供されたクラス `A` についてその方法を適用しようとした場合に、当該クラスが `operator new` を提供していると、たとえそのシグネチャが `operator new(std::size_t, void*)` ではないとしても `new A(p)` がオーバーロードの解決に失敗して（グローバルな `::operator new` が見えなくなってしまうため）エラーとなってしまい、無駄に悩まされてしまうためです。

C++ を学習した人が、たとえその後自らは一生 `operator new` を書くことが無い（あるいはむしろそのようなものの存在を学習すらしない）としても、「指定されたアドレスにオブジェクトを構築する方法」は（たった 2 文字追加された形式の） `::new A(p)` であると覚えてさえいれば、そのような無駄を避けさせることができると思いますし、学習意欲の高い人がその後「今まで `new A(p)` って書いてたけどあれは `::new A(p)` と書くべきだった。直さなきゃ」と考えさせることも回避できると思います。

なお、私としては、「指定されたアドレスにオブジェクトを構築する方法」 として `new A(p)` と記載されている書籍や記事ばかりでいつもとても悲しい気持ちになっていたので、コメントさせて頂きましたが、もちろん最終的にはお任せいたします。

ちなみに完全に余談ですが、実は規格も C++03 までは `std::allocator::allocate` が `new A(p)` を使っている出来の悪い子でした…（C++11 以降では直っています）

**Comment by starpos** [comment]
ご主張は、詳しいことを知らない人が最初に配置 new の使い方を覚えるときは、`new(p) A` ではなく `::new(p) A` で覚えるべきだ、ということですね。
配置 new ではない通常の operator new のみユーザー定義したら `new(p) A` は存在しなくなってハマるということですね。配置 new を自分で定義したくなる理由はないので `::new(p) A` と書くべきだと。

operator new をユーザー定義するときは配置 new のオーバーロードも必ず定義する、中身は `::new` を呼ぶだけ、という回避策でも成立する気はしますが、筋悪、かなぁ。。。

ということで、`::new` を採用させていただきます。教えて下さってありがとうございました。

...そもそも名前空間を先に解決してからオーバーロードを探すという挙動がどうなのかという感じ。。。継承で無駄にフォワードするだけのコードを書いたことがあります。深淵な理由があるのかも知れませんが。

**Comment by starpos** [comment]
7e378de4631b81a811bbc1a1eda7f624f0f7f1e1
こんな感じ。

**Comment by starpos** [comment]
(別のコメント書いたのに github の調子が悪くて消えました。。)

ご主張は理解しました。operator new を定義したときは void* operator new(size_t, void*) も明示的に定義しないと `new(p) A` と書いたときに `::new` は見えなくなってしまうということですね。で、わざわざ placement new 用の operator new を書くとかバッドノウハウなので、だったら最初から `::new` を使わせとけと。

ということで、placement new は `::new` をデフォルトにする案を採用させていただきます。
ご指摘ありがとうございました。

**Comment by kariya-mitsuru** [comment]
いろいろとお手数をおかけしました。
少なくとも私の感覚では修正して頂いた説明がちょうど必要十分に感じました。

> operator new をユーザー定義するときは配置 new のオーバーロードも必ず定義する、中身は `::new` を呼ぶだけ、という回避策でも成立する気はしますが、筋悪、かなぁ。。。

私も（C++03 の `std::allocator::allocate` の件があったので）昔はそんな風に思ったこともありましたが、いろいろ悩んだ結果 `::new` にすべきとの意見に落ち着きました。

重ね重ねご対応ありがとうございました。
